import { createFileRoute } from "@tanstack/react-router";
import { Upload } from "lucide-react";
import { PageHero, Mono } from "@/components/primitives";

export const Route = createFileRoute("/map")({
  head: () => ({
    meta: [
      { title: "Interactive map — GraphSAGE Food Desert Identification" },
      {
        name: "description",
        content:
          "Predicted-vs-true food-environment labels across Bengaluru, rendered from the Folium HTML map produced by Notebook 08.",
      },
    ],
  }),
  component: MapPage,
});

const MAP_SRC = "/maps/adaptive_hex_pred_vs_true_map.html";

function MapPage() {
  return (
    <div>
      <PageHero
        eyebrow="Interactive map"
        title="Predicted vs true labels across Bengaluru."
        lede="The map below is the Folium output from Notebook 08 — the adaptive-hex target pipeline. Each polygon is one of the 1,012 adaptive food-access units, coloured by its true label and the model's prediction."
      />

      <div className="mx-auto max-w-6xl px-6 py-10">
        <div className="overflow-hidden rounded-md border bg-card">
          <iframe
            src={MAP_SRC}
            title="Adaptive hex prediction map"
            className="block h-[720px] w-full"
            sandbox="allow-scripts allow-same-origin allow-popups"
            onError={(e) => console.error("map load", e)}
          />
        </div>

        <details className="mt-6 rounded-md border bg-muted/40 p-5 text-sm text-muted-foreground">
          <summary className="cursor-pointer font-medium text-foreground">
            <Upload className="mr-2 inline h-4 w-4" />
            Map not loading? How to add the Folium HTML
          </summary>
          <div className="mt-4 space-y-3">
            <p>
              Drop the Folium HTML files generated by Notebook 08 into the project at:
            </p>
            <Mono>public/maps/adaptive_hex_pred_vs_true_map.html</Mono>
            <p>
              The expected files are{" "}
              <Mono>outputs/adaptive_hex_pred_vs_true_map.html</Mono> and{" "}
              <Mono>outputs/08_adaptive_vs_03_series_interactive_map.html</Mono>{" "}
              from the thesis repo. Once present, this iframe will pick them up
              automatically — no further wiring needed.
            </p>
          </div>
        </details>

        <div className="mt-10 grid gap-6 md:grid-cols-3">
          <Stat label="Adaptive units" value="1,012" hint="From 1,496 source hexes" />
          <Stat label="Best macro-F1" value="0.793" hint="Gradient Boosting · spatial holdout" />
          <Stat label="Best accuracy" value="0.939" hint="Gradient Boosting · high-confidence split" />
        </div>
      </div>
    </div>
  );
}

function Stat({ label, value, hint }: { label: string; value: string; hint: string }) {
  return (
    <div className="rounded-md border bg-card p-5">
      <p className="smallcaps text-[10px] text-muted-foreground">{label}</p>
      <p className="metric-num mt-2 text-3xl text-foreground">{value}</p>
      <p className="mt-1 text-xs text-muted-foreground">{hint}</p>
    </div>
  );
}
