/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as TargetRouteImport } from './routes/target'
import { Route as ScenarioLabRouteImport } from './routes/scenario-lab'
import { Route as ScenarioRouteImport } from './routes/scenario'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as RunRouteImport } from './routes/run'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as MapRouteImport } from './routes/map'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComparisonRouteImport } from './routes/comparison'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as CheckpointsRouteImport } from './routes/checkpoints'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotebooksIndexRouteImport } from './routes/notebooks.index'
import { Route as TrainingBengaluruRouteImport } from './routes/training.bengaluru'
import { Route as NotebooksIdRouteImport } from './routes/notebooks.$id'
import { Route as CityIdRouteImport } from './routes/city.$id'

const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetRoute = TargetRouteImport.update({
  id: '/target',
  path: '/target',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioLabRoute = ScenarioLabRouteImport.update({
  id: '/scenario-lab',
  path: '/scenario-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioRoute = ScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonRoute = ComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckpointsRoute = CheckpointsRouteImport.update({
  id: '/checkpoints',
  path: '/checkpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksIndexRoute = NotebooksIndexRouteImport.update({
  id: '/notebooks/',
  path: '/notebooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingBengaluruRoute = TrainingBengaluruRouteImport.update({
  id: '/training/bengaluru',
  path: '/training/bengaluru',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksIdRoute = NotebooksIdRouteImport.update({
  id: '/notebooks/$id',
  path: '/notebooks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CityIdRoute = CityIdRouteImport.update({
  id: '/city/$id',
  path: '/city/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/checkpoints': typeof CheckpointsRoute
  '/cities': typeof CitiesRoute
  '/comparison': typeof ComparisonRoute
  '/dashboard': typeof DashboardRoute
  '/exports': typeof ExportsRoute
  '/features': typeof FeaturesRoute
  '/locations': typeof LocationsRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/readiness': typeof ReadinessRoute
  '/results': typeof ResultsRoute
  '/run': typeof RunRoute
  '/runs': typeof RunsRoute
  '/scenario': typeof ScenarioRoute
  '/scenario-lab': typeof ScenarioLabRoute
  '/target': typeof TargetRoute
  '/validation': typeof ValidationRoute
  '/city/$id': typeof CityIdRoute
  '/notebooks/$id': typeof NotebooksIdRoute
  '/training/bengaluru': typeof TrainingBengaluruRoute
  '/notebooks/': typeof NotebooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/checkpoints': typeof CheckpointsRoute
  '/cities': typeof CitiesRoute
  '/comparison': typeof ComparisonRoute
  '/dashboard': typeof DashboardRoute
  '/exports': typeof ExportsRoute
  '/features': typeof FeaturesRoute
  '/locations': typeof LocationsRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/readiness': typeof ReadinessRoute
  '/results': typeof ResultsRoute
  '/run': typeof RunRoute
  '/runs': typeof RunsRoute
  '/scenario': typeof ScenarioRoute
  '/scenario-lab': typeof ScenarioLabRoute
  '/target': typeof TargetRoute
  '/validation': typeof ValidationRoute
  '/city/$id': typeof CityIdRoute
  '/notebooks/$id': typeof NotebooksIdRoute
  '/training/bengaluru': typeof TrainingBengaluruRoute
  '/notebooks': typeof NotebooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/checkpoints': typeof CheckpointsRoute
  '/cities': typeof CitiesRoute
  '/comparison': typeof ComparisonRoute
  '/dashboard': typeof DashboardRoute
  '/exports': typeof ExportsRoute
  '/features': typeof FeaturesRoute
  '/locations': typeof LocationsRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/readiness': typeof ReadinessRoute
  '/results': typeof ResultsRoute
  '/run': typeof RunRoute
  '/runs': typeof RunsRoute
  '/scenario': typeof ScenarioRoute
  '/scenario-lab': typeof ScenarioLabRoute
  '/target': typeof TargetRoute
  '/validation': typeof ValidationRoute
  '/city/$id': typeof CityIdRoute
  '/notebooks/$id': typeof NotebooksIdRoute
  '/training/bengaluru': typeof TrainingBengaluruRoute
  '/notebooks/': typeof NotebooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/audit'
    | '/checkpoints'
    | '/cities'
    | '/comparison'
    | '/dashboard'
    | '/exports'
    | '/features'
    | '/locations'
    | '/map'
    | '/methodology'
    | '/readiness'
    | '/results'
    | '/run'
    | '/runs'
    | '/scenario'
    | '/scenario-lab'
    | '/target'
    | '/validation'
    | '/city/$id'
    | '/notebooks/$id'
    | '/training/bengaluru'
    | '/notebooks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audit'
    | '/checkpoints'
    | '/cities'
    | '/comparison'
    | '/dashboard'
    | '/exports'
    | '/features'
    | '/locations'
    | '/map'
    | '/methodology'
    | '/readiness'
    | '/results'
    | '/run'
    | '/runs'
    | '/scenario'
    | '/scenario-lab'
    | '/target'
    | '/validation'
    | '/city/$id'
    | '/notebooks/$id'
    | '/training/bengaluru'
    | '/notebooks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/audit'
    | '/checkpoints'
    | '/cities'
    | '/comparison'
    | '/dashboard'
    | '/exports'
    | '/features'
    | '/locations'
    | '/map'
    | '/methodology'
    | '/readiness'
    | '/results'
    | '/run'
    | '/runs'
    | '/scenario'
    | '/scenario-lab'
    | '/target'
    | '/validation'
    | '/city/$id'
    | '/notebooks/$id'
    | '/training/bengaluru'
    | '/notebooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuditRoute: typeof AuditRoute
  CheckpointsRoute: typeof CheckpointsRoute
  CitiesRoute: typeof CitiesRoute
  ComparisonRoute: typeof ComparisonRoute
  DashboardRoute: typeof DashboardRoute
  ExportsRoute: typeof ExportsRoute
  FeaturesRoute: typeof FeaturesRoute
  LocationsRoute: typeof LocationsRoute
  MapRoute: typeof MapRoute
  MethodologyRoute: typeof MethodologyRoute
  ReadinessRoute: typeof ReadinessRoute
  ResultsRoute: typeof ResultsRoute
  RunRoute: typeof RunRoute
  RunsRoute: typeof RunsRoute
  ScenarioRoute: typeof ScenarioRoute
  ScenarioLabRoute: typeof ScenarioLabRoute
  TargetRoute: typeof TargetRoute
  ValidationRoute: typeof ValidationRoute
  CityIdRoute: typeof CityIdRoute
  NotebooksIdRoute: typeof NotebooksIdRoute
  TrainingBengaluruRoute: typeof TrainingBengaluruRoute
  NotebooksIndexRoute: typeof NotebooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/target': {
      id: '/target'
      path: '/target'
      fullPath: '/target'
      preLoaderRoute: typeof TargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario-lab': {
      id: '/scenario-lab'
      path: '/scenario-lab'
      fullPath: '/scenario-lab'
      preLoaderRoute: typeof ScenarioLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario': {
      id: '/scenario'
      path: '/scenario'
      fullPath: '/scenario'
      preLoaderRoute: typeof ScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison': {
      id: '/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkpoints': {
      id: '/checkpoints'
      path: '/checkpoints'
      fullPath: '/checkpoints'
      preLoaderRoute: typeof CheckpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks/': {
      id: '/notebooks/'
      path: '/notebooks'
      fullPath: '/notebooks/'
      preLoaderRoute: typeof NotebooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/bengaluru': {
      id: '/training/bengaluru'
      path: '/training/bengaluru'
      fullPath: '/training/bengaluru'
      preLoaderRoute: typeof TrainingBengaluruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks/$id': {
      id: '/notebooks/$id'
      path: '/notebooks/$id'
      fullPath: '/notebooks/$id'
      preLoaderRoute: typeof NotebooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$id': {
      id: '/city/$id'
      path: '/city/$id'
      fullPath: '/city/$id'
      preLoaderRoute: typeof CityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuditRoute: AuditRoute,
  CheckpointsRoute: CheckpointsRoute,
  CitiesRoute: CitiesRoute,
  ComparisonRoute: ComparisonRoute,
  DashboardRoute: DashboardRoute,
  ExportsRoute: ExportsRoute,
  FeaturesRoute: FeaturesRoute,
  LocationsRoute: LocationsRoute,
  MapRoute: MapRoute,
  MethodologyRoute: MethodologyRoute,
  ReadinessRoute: ReadinessRoute,
  ResultsRoute: ResultsRoute,
  RunRoute: RunRoute,
  RunsRoute: RunsRoute,
  ScenarioRoute: ScenarioRoute,
  ScenarioLabRoute: ScenarioLabRoute,
  TargetRoute: TargetRoute,
  ValidationRoute: ValidationRoute,
  CityIdRoute: CityIdRoute,
  NotebooksIdRoute: NotebooksIdRoute,
  TrainingBengaluruRoute: TrainingBengaluruRoute,
  NotebooksIndexRoute: NotebooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
